import Head from 'next/head'
import { styled } from '@stitches/react'
import { amber, mauve, orange, orangeA, purpleDark, purple, violet, blackA } from '@radix-ui/colors'


const Header = styled('div', {
  display: 'flex',
  flexDirection: 'row',
  maxWidth: 1400,
  flexGrow: 1,
  flexShrink: 1,
  flexSasis: 0,
  paddingTop: 16,
  paddingRight: 34,
  paddingBottom: 16,
  paddingLeft: 34,
})

const Center = styled('div', {
  display: "flex",
  justifyContent: "center",
  alignItems: "center"
})


const Button = styled('button', {
  all: 'unset',
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  borderRadius: 12,
  padding: '0 15px',
  fontSize: 15,
  lineHeight: 1,
  fontWeight: 500,
  height: 35,
  transition: "0.4s ease all",
  cursor: "pointer",

  variants: {
    size: {
      md: {
        height: 35
      },
      lg: {
        height: 40,
      }
    },
    variant: {
      default: {
        color: mauve.mauve11,
        '&:hover': {
          transition: "0.4s ease all",
          color: mauve.mauve12,
        }
      },
      primary: {
        backgroundColor: orange.orange9,
        color: "white",
        '&:hover': {
          transition: "0.4s ease all",
          transform: "translate(1px, -1px)",
          boxShadow: `${orangeA.orangeA5} 0px 6px 24px, ${orangeA.orangeA5} 1px 4px 12px`,
        }
      },
      white: {
        backgroundColor: 'white',
        color: mauve.mauve12,
        '&:hover': {
          transition: "0.4s ease all",
          transform: "translate(1px, -1px)",
        }

      }
    }
  },

  defaultVariants: {
    variant: "default",
    size: "md"
  }
})


const Link = styled('a', {
  cursor: 'pointer',
  fontWeight: 500,
  padding: 0
})


const Input = styled('input', {
  all: 'unset',
  flex: '1 0 auto',
  borderRadius: 8,
  padding: '0 10px',
  fontSize: 15,
  lineHeight: 1,
  boxSizing:"border-box",
  color: mauve.mauve12,
  background: mauve.mauve2,
  textAlign: "left",
  boxShadow: `0 0 0 1px ${mauve.mauve4}`,
  height: 35,
  width:"100%",
  '&:focus': { boxShadow: `0 0 0 2px ${mauve.mauve7}` },
});

const Box = styled('div')

const Label = styled('label', {
  textAlign:"left",
  marginTop: 10,
  fontWeight: 500,
  color: mauve.mauve12
})

export default function Home() {
  // const router = useRouter();


  // let { data, status, } = useSession({
  //   required: true
  // });

  // if (status == 'loading') {
  //   return <div style={{ width: "100vw", position: "fixed", top: 0, left: 0, height: "100vh", display: "flex", justifyContent: "center", alignItems: "center" }}>
  //     <H2>Insource Talent</H2>
  //   </div>
  // }


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* <Header>
          <div>
            LOGO
          </div>
          <div style={{flexGrow:1, flexShrink:1, flexBasis:"auto"}}></div>
          <Center style={{  justifyContent: "space-around", gap:15 }}>
            <Link>Our features</Link>
            <Link>Who need us</Link>
            <Link>Special benefits</Link>
            <Link>Pricing</Link>
            <Link>Contact us</Link>
          </Center>
          <div style={{flexGrow:1, flexShrink:1, flexBasis:"auto"}}></div>
          <div>
            <Button>Login</Button>
            <Button variant={'primary'}>Sign up</Button>
          </div>
        </Header> */}
        <div style={{ width: "100vw", background:`linear-gradient(40deg, ${purple.purple12}, ${violet.violet10})`, height: '100vh', padding: "5%", display: "flex", justifyContent: "center", alignItems: "center" }}>
          <Box style={{
            background: mauve.mauve1, display: "flex", gap: 5, flexDirection: "column", textAlign: "center", borderRadius: 18,
            boxShadow: `${blackA.blackA3} 0px 0px 0px 2px`,
            padding: 40, maxWidth: 460, width: "100%", border: `1px solid ${mauve.mauve2}`
          }}>
            <h2 style={{ color: violet.violet10, marginBottom: 5 }}>Create an Account</h2>
            <span style={{ color: mauve.mauve12 }}>Already have an account ? <Link css={{ color: violet.violet10 }}>Login</Link></span>
            <br />

            <Box css={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, textAlign:"left" }}>
              <div style={{display:"flex", flexDirection:"column", gap:5,}}>
                <Label style={{ textAlign: "left" }}>Commercial name</Label>
                <Input placeholder='' ></Input>
              </div>
            
              <div style={{display:"flex", flexDirection:"column", gap:5,}}>
                <Label style={{ textAlign: "left" }}>Your name</Label>
                <Input placeholder='johndoe' ></Input>
              </div>
            </Box>


            <Label style={{ textAlign: "left" }}>Email</Label>
            <Input placeholder='johndoe@gmail.com' ></Input>

            <Label style={{ textAlign: "left" }}>Phone</Label>
            <Input placeholder='+84' ></Input>

            <Label style={{ textAlign: "left" }}>Username</Label>
            <Input placeholder='enter username' ></Input>

            <Label style={{ textAlign: "left" }}>Password</Label>
            <Input placeholder='enter password' type='password' ></Input>

            <br/>
            <Button variant='primary'>Sign up</Button>
          </Box>
        </div>
      </div>
    </div>




  )
}


// Home.getLayout = (page) => {
//   return <DashboardLayout>
//       {page}
//   </DashboardLayout>
// }